name: Check-and-Activate-Dependabot-Alerts

on:
  workflow_dispatch:

jobs:
  checker:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1 # v1.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.INSTALLATION_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Get Dependabot alerts status
        id: dependabot-status
        run: |
          curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $GH_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/FilippoBau/selfcare-ms-core/dependabot/alerts
        env:
          GH_TOKEN: ${{ steps.get_token.outputs.token }}


      - name: Activate Dependabot alerts if not enabled
        if: ${{steps.dependabot-status.outputs.status}} == "403"
        run: |
          curl -L -X PUT -i -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/FilippoBau/selfcare-ms-core/vulnerability-alerts
        env:
          GH_TOKEN: ${{ steps.get_token.outputs.token }}
