name: Check-and-Activate-Dependabot-Alerts

on:
  workflow_dispatch:

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # v1.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.INSTALLATION_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Get Dependabot alerts status
        id: dependabot-status
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $GH_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/FilippoBau/selfcare-ms-core/dependabot/alerts)
          echo $status
        env:
          GH_TOKEN: ${{ steps.get_token.outputs.token }}


      - name: Activate Dependabot alerts if not enabled
        if: ${{steps.dependabot-status.outputs.status}} == "403"
        run: |
          status=$(curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com//repos/FilippoBau/selfcare-ms-core/vulnerability-alerts)
          echo $status
        env:
          GH_TOKEN: ${{ steps.get_token.outputs.token }}
