name: Check-and-Activate-Dependabot-Alerts

on:
  workflow_call:
    inputs:
      configurationFile:
        description: "Configuration file"
        required: true
        type: string

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1 # v1.7.0
        with:
          app-id: ${{ secrets.APP_ID }}
          owner: ${{ github.repository_owner }}
          private-key: ${{ secrets.PRIVATE_KEY }}        
          
      - name: Read repo and enable
        id: read_renovate
        run: |
          repositories=$(jq -r '.repositories[]' $CONF)
          echo $repositories
          for repo in ${repositories[@]}; do
            echo '1'
            echo 'test'
            status=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/$repo/vulnerability-alerts --silent 2>&1 || true)
            echo "test"
            echo $status
            if [ "$status" = "gh: Vulnerability alerts are disabled. (HTTP 404)" ]; then
              echo '2'
              gh api --method PUT -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/$repo/vulnerability-alerts
            else
              echo '3'
              status=$(gh api --method GET -H "Accept: application/vnd.github.v3+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/$repo/automated-security-fixes | jq -r '.enabled')
              if [ "$status" = "true" ]; then
                echo $status
                gh api --method DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/$repo/automated-security-fixes
              fi
            fi
          done
        env:
          GH_TOKEN: ${{ steps.get_token.outputs.token }}
          CONF: ${{ inputs.configurationFile }}

     
