name: Interop
on:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: FilippoBau/Prodsectest/.github/workflows/renovate.yml@main
    with:
      #### REMEMBER TO CHANGE ######
      configurationFile: "Interop-temp/renovate.json"
      dirtyRun: "full"
    secrets: inherit

