name: Interop
on:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: FilippoBau/Prodsectest/.github/workflows/renovate.yml@main
    with:
      configurationFile: "Interop/renovate.json"
    secrets: inherit

