name: Parallel prodcut
on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Run renovate in DirtyRun mode"
        required: false
        default: "full"
        type: string

jobs:
  run-script:
    runs-on: ubuntu-22.04
    environment: renovate
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Json-Splitter
        id: jsonSplitter
        run: |
          echo "Run script"
          cd ./utils/repo-splitter/
          ls .
          ./json-splitter.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shared-json-files
          path: |
            jsonRepo1.json
            jsonRepo2.json
  dependabot-check:
    needs: run-script
    strategy:
      matrix:
        configurationFile: ["./jsonRepo1.json", "./jsonRepo2.json"]
    uses: FilippoBau/Prodsectest/.github/workflows/dependabot-check.yml@main
    with:
      configurationFile: ${{ matrix.configurationFile }}
    secrets: inherit 
  pr-closer:
    needs: run-script
    strategy:
      matrix:
        configurationFile: ["./jsonRepo1.json", "./jsonRepo2.json"] 
    uses: FilippoBau/Prodsectest/.github/workflows/pr-closer.yml@main
    with:
      configurationFile: ${{ matrix.configurationFile }}
    secrets: inherit
  run-renovate:
    needs: [dependabot-check,pr-closer]
    strategy:
      matrix:
        configurationFile: ["./jsonRepo1.json", "./jsonRepo2.json"] 
    uses: FilippoBau/Prodsectest/.github/workflows/renovate.yml@main
    with:
      configurationFile: ${{ matrix.configurationFile }}
      dryRun: ${{inputs.dryRun ||'null'}}
    secrets: inherit
