name: Parallel prodcut
on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Run renovate in DirtyRun mode"
        required: false
        default: "full"
        type: string

jobs:
  call_workflow-1:
    strategy:
      matrix:
        configurationFile: ["./parallel_test1.json", "./parallel_test2.json"]
    uses: FilippoBau/Prodsectest/.github/workflows/dependabot-check.yml@main
    with:
      configurationFile: ${{ matrix.configurationFile }}
    secrets: inherit 
  call_workflow-2:
    strategy:
      matrix:
        configurationFile: ["./parallel_test1.json", "./parallel_test2.json"]  
    uses: FilippoBau/Prodsectest/.github/workflows/pr-closer.yml@main
    with:
      configurationFile: ${{ matrix.configurationFile }}
    secrets: inherit
  call_workflow-3:
    strategy:
      matrix:
        configurationFile: ["./parallel_test1.json", "./parallel_test2.json"]  
    uses: FilippoBau/Prodsectest/.github/workflows/renovate.yml@main
    with:
      configurationFile: ${{ matrix.configurationFile }}
      dryRun: ${{inputs.dryRun ||'null'}}
    secrets: inherit
