name: Parallel prodcut
on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Run renovate in DirtyRun mode"
        required: false
        default: "full"
        type: string

jobs:
  run-script:
    runs-on: ubuntu-22.04
    environment: renovate
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Json-Splitter
        id: jsonSplitter
        run: |
          echo "Run script"
          cd ./utils/repo-splitter/
          ls .
          chmod +x json-splitter.sh
          ./json-splitter.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shared-json-files
          path: |
            utils/repo-splitter/jsonRepo1.json
            utils/repo-splitter/jsonRepo2.json
  run-renovate:
    needs: [run-script]
    strategy:
      matrix:
        configurationFile: ["jsonRepo1.json", "jsonRepo2.json"]
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Download JSON files
        uses: actions/download-artifact@v3
        with:
          name: shared-json-files
      - name: Run renovate
        uses: ./.github/workflows/renovate
        with:
          configurationFile: ${{ matrix.configurationFile }}
          dryRun: ${{inputs.dryRun ||'null'}}
          debug: ${{ inputs.debug ||'null'}}
         
