name: Renovate
on:
  workflow_call:
    inputs:
      configurationFile:
        description: "Configuration file"
        required: true
        type: string
concurrency: renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        # Don't waste time starting Renovate if JSON is invalid
      - name: Validate Renovate JSON
        run: jq type $CONF
        env:
          CONF: ${{ inputs.configurationFile }}
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # v1.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.INSTALLATION_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.4
        env:
          # Username for GitHub authentication (should match GitHub App name + [bot])
          RENOVATE_USERNAME: "renovate-auth[bot]"
          # Git commit author used, must match GitHub App
          RENOVATE_GIT_AUTHOR: "renovate-auth <162982637+renovate-auth[bot]@users.noreply.github.com>"
          # Use GitHub API to create commits (this allows for signed commits from GitHub App)
          RENOVATE_PLATFORM_COMMIT: "true"
          # Onboarding not needed for self hosted
          RENOVATE_ONBOARDING: "false"
          RENOVATE_REQUIRE_CONFIG: "optional"
          RENOVATE_PR_HOURLY_LIMIT: 0
          RENOVATE_PR_CONCURRENT_LIMIT: 5
          # Put dryrun option in the caller pipeline as input
          #RENOVATE_DRY_RUN: "full"
          #RENOVATE_LOG_FILE: '/tmp/renovate/results.json'
          #LOG_LEVEL: "DEBUG"
        with:
          configurationFile: ${{ inputs.configurationFile }}
          token: '${{ steps.get_token.outputs.token }}'
      #- name: Upload Artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: my-artifact
      #    path: /tmp/renovate/results.json
      #    retention-days: 5


    
