name: Selfcare
on:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: FilippoBau/Prodsectest/.github/workflows/renovate.yml@main
    with:
      configurationFile: "Selfcare/renovate.json"
  #secrets: inherit
  #DA VALUTARE SINGOLA PIPELINE CON PIU JOBS(UN JOB PER OGNI PRODOTTO) CON CLAUSOLA 'IF: ALWAYS()'
