name: Selfcare

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Run renovate in Dryrun mode"
        required: false
        default: "full"
        type: string
      debug:
        description: "Run renovate in debug mode"
        required: false
        default: "INFO"
        type: string

        
jobs:
  call_workflow-3:
    uses: pagopa/eng-renovate/.github/workflows/action-renovate.yml@main
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dryRun == 'full' }}
    with:
      configurationFile: "./dryRun-renovate.json"
      dryRun: 'full'
      debug:  ${{ github.event.inputs.debug || 'INFO' }}
    secrets: inherit
  call_workflow-4:
    uses: pagopa/eng-renovate/.github/workflows/action-renovate.yml@main
    if: ${{ github.event_name == 'schedule' || github.event.inputs.dryRun != 'full' }}
    with:
      configurationFile: "./selfcare-renovate.json"
      dryRun: ${{ inputs.dryRun || 'null' }}
      debug:  ${{ github.event.inputs.debug || 'INFO' }}
    secrets: inherit
    
