name: Selfcare
on:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: FilippoBau/Prodsectest/.github/workflows/dependabot-check.yml@main
    with:
      configurationFile: "Selfcare/renovate.json"
    secrets: inherit
