name: Selfcare

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Run renovate in Dryrun mode"
        required: false
        default: "full"
        type: string
      debug:
        description: "Run renovate in debug mode"
        required: false
        default: "INFO"
        type: string

        
jobs:

  call_workflow-4:
    uses: FilippoBau/Prodsectest/.github/workflows/parallel-renovate.yml@main
    with:
      configurationFile: "./selfcare-renovate.json"
      dryRun: ${{ inputs.dryRun || 'null' }}
      debug:  ${{ github.event.inputs.debug || 'INFO' }}
    secrets: inherit
    
