name: Renovate-SELFCARE
on:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: FilippoBau/.github/renovate.yml
    with:
      configurationFile: "Selfcare/renovate.json"
  #secrets: inherit
  #DA VALUTARE SINGOLA PIPELINE CON PIU JOBS(UN JOB PER OGNI PRODOTTO) CON CLAUSOLA 'IF: ALWAYS()'
