name: Test

on:
  schedule:
    - cron: '* * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run a script
      run: echo "Running scheduled task"
